module.exports = {
  type: "object",
  properties: {
    bmsUrl: {
      title: "BMS WebSocket URL",
      type: "string",
      default: "ws://WiFi-module-ip/ws"
    },
    deltaPrefix: {
      title: "Delta Path Prefix",
      type: "string",
      default: "electrical.batteries.bms"
    },
    statusDeltas: {
      title: "Status Delta Options",
      type: "object",
      properties: {
        vbat: { type: "boolean", title: "Voltage", default: true },
        ibat: { type: "boolean", title: "Current", default: true },
        wbat: { type: "boolean", title: "Power", default: true },
        mincell: { type: "boolean", title: "Min Cell Voltage", default: true },
        maxcell: { type: "boolean", title: "Max Cell Voltage", default: true },
        res: { type: "boolean", title: "Cell Resistance (all)", default: true },
        temp: { type: "boolean", title: "Cell Temperature (all)", default: true },
        nap: { type: "boolean", title: "Cell Voltage (all)", default: true },
        cvd: { type: "boolean", title: "Cell Voltage Difference", default: true },
        soc: { type: "boolean", title: "State Of Charge", default: true },
        soh: { type: "boolean", title: "State Of Health", default: true },
        time_remaining: { type: "boolean", title: "Time to 0% SOC Remaining", default: true },
        temp_bms: { type: "boolean", title: "BMS Temperature", default: true },
        erro_present: { type: "boolean", title: "Error Present", default: false },
        erro_addr: { type: "boolean", title: "Error Address", default: false },
        erro_con_st: { type: "boolean", title: "Error Connection State", default: false },
        erro_st: { type: "boolean", title: "Error Status", default: false },
        error: { type: "boolean", title: "Error Message", default: false },
        slaveAddress: { type: "boolean", title: "Slave Address", default: false },
        st_celic: { type: "boolean", title: "Slave Cell Count", default: false },
        st_temp: { type: "boolean", title: "Slave Temp Sensor Status", default: false },
        st_naprav: { type: "boolean", title: "UNKNOWN", default: false },
      }
    },
    settingsDeltas: {
      title: "Settings Delta Options",
      type: "object",
      properties: {
        AhR: { type: "boolean", title: "Amp Hours Remaining", default: true },
        bvol: { type: "boolean", title: "Balancing END Voltage", default: false },
        bmin: { type: "boolean", title: "Balancing START Voltage", default: false },
        razl: { type: "boolean", title: "Max Allowed Cell Voltage Difference", default: false },
        char: { type: "boolean", title: "End Of Charge Voltage", default: false },
        chis: { type: "boolean", title: "End of Charging Voltage Hysteresis", default: false },
        cmax: { type: "boolean", title: "Max Allowed Cell Voltage", default: false },
        maxh: { type: "boolean", title: "Max Allowed Cell Voltage Hysteresis", default: false },
        cmin: { type: "boolean", title: "Min Allowed Cell Voltage", default: false },
        minh: { type: "boolean", title: "Min Allowed Cell Voltage Hysteresis", default: false },
        clow: { type: "boolean", title: "Min Allowed Cell Discharge", default: false },
        cfvc: { type: "boolean", title: "Float Voltage Coefficient", default: false },
        ioja: { type: "boolean", title: "Current Sensor Coefficient", default: false },
        ioff: { type: "boolean", title: "Current Sensor Offset", default: false },
        maxc: { type: "boolean", title: "Max Charge Current", default: false },
        maxd: { type: "boolean", title: "Max Discharge Current", default: false },
        chac: { type: "boolean", title: "Charging Coefficient", default: false },
        dchc: { type: "boolean", title: "Discharge Coefficient", default: false },
        tmin: { type: "boolean", title: "minAllowedChargeTemp", default: false },
        tmax: { type: "boolean", title: "maxAllowedChargeTemp", default: false },
        tbal: { type: "boolean", title: "maxAllowedBMSTemp", default: false },
        bmth: { type: "boolean", title: "maxAllowedBMSHysteresis", default: false },
        mcu_date: { type: "boolean", title: "BMS Date", default: false },
        mcu_time: { type: "boolean", title: "BMS Time", default: false },
        bms_name: { type: "boolean", title: "BMS Name", default: true },
        cycl: { type: "boolean", title: "Battery Cycle Count", default: true },
        capa: { type: "boolean", title: "Capacity", default: false },
        chem: { type: "boolean", title: "Chemistry", default: false },
        addr: { type: "boolean", title: "Address", default: false },
        tunit: { type: "boolean", title: "T-unit", default: false },
        cmin: { type: "boolean", title: "Min Allowed Cell Voltage", default: false },
        cmax: { type: "boolean", title: "Max Allowed Cell Voltage", default: false },
        //cur:  { type: "boolean", title: "Current 2", default: false },
        new_log_every_midnight: { type: "boolean", title: "New Log Every Midnight", default: false },
        out: { type: "boolean", title: "Out", default: false },
        cans: { type: "boolean", title: "Can Bus Protocol", default: false },
        lcd: { type: "boolean", title: "LCD Baud Rate", default: false },
        com: { type: "boolean", title: "Com Baud Rate", default: false },
        p: { type: "boolean", title: "Error Presence Flag", default: false },
        num: { type: "boolean", title: "Error Number", default: false },
        op2h: { type: "boolean", title: "Op2H", default: false },
        op2l: { type: "boolean", title: "Op2L", default: false },
        op2t: { type: "boolean", title: "Op2T", default: false },
        op2v: { type: "boolean", title: "Op2V", default: false },
        re1h: { type: "boolean", title: "Re1H", default: false },
        re1l: { type: "boolean", title: "Re1L", default: false },
        re1t: { type: "boolean", title: "Re1T", default: false },
        re1v: { type: "boolean", title: "Re1V", default: false },
        socs: { type: "boolean", title: "SoCs", default: false },
        soch: { type: "boolean", title: "SoCh", default: false },
        strn: { type: "boolean", title: "Strn", default: false },
        rsbr: { type: "boolean", title: "Rsbr", default: false },
        errorGroup: { type: "boolean", title: "Error Group", default: false },
        nncGroup:   { type: "boolean", title: "Nearest Neighbor Group", default: false },
        vncGroup:   { type: "boolean", title: "Vnc Group", default: false },
        toorGroup:  { type: "boolean", title: "Toor Group", default: false },
        baudGroup:  { type: "boolean", title: "Baud Group", default: false }
      }
    }
  }
};
